-- Migração dos endereços legados (endereco_202606112247.json) para a tabela `addresses`.
-- tipo -> address_type, nome -> name (espaços nas bordas removidos), descricao -> notes (vazia -> NULL).
-- Ids legados preservados (9, 50, 61, 65, 79, 81 não existiam na origem) para manter o vínculo com `links.address_id`.
-- O id 66 (' Água Nova') é duplicata do id 52 após o trim e foi OMITIDO: o índice único
-- (address_type, name) vale também para registros soft-deletados, então nem soft-deletada a
-- duplicata pode existir. As ligações que apontavam para o 66 são repontadas para o 52 no
-- insert_links.sql (ids 1900 e 2139).

INSERT INTO addresses
  (id, address_type, name, notes, created_at, updated_at)
VALUES
  (1,   'Rua',      'Alegria', NULL, NOW(), NOW()),
  (2,   'Travessa', 'Alegria', NULL, NOW(), NOW()),
  (3,   'Rua',      'ACM', NULL, NOW(), NOW()),
  (4,   'Travessa', 'ACM', NULL, NOW(), NOW()),
  (5,   'Rua',      'Bom Sucesso', NULL, NOW(), NOW()),
  (6,   'Travessa', 'Bom Sucesso', NULL, NOW(), NOW()),
  (7,   'Rua',      'Coronel S. Nogueira', NULL, NOW(), NOW()),
  (8,   'Rua',      'Edivaldo Nunes de Carvalho', NULL, NOW(), NOW()),
  (10,  'Avenida',  'Fernando Daltro', NULL, NOW(), NOW()),
  (11,  'Travessa', 'Fernando Daltro', NULL, NOW(), NOW()),
  (12,  'Avenida',  'Flavio Mesquita', NULL, NOW(), NOW()),
  (13,  'Travessa', 'Flavio Mesquita', NULL, NOW(), NOW()),
  (14,  'Rua',      'Flores', NULL, NOW(), NOW()),
  (15,  'Travessa', 'Flores', NULL, NOW(), NOW()),
  (16,  'Rua',      'Gilberto Miranda', NULL, NOW(), NOW()),
  (17,  'Rua',      'Jose Facho', NULL, NOW(), NOW()),
  (18,  'Rua',      'João Neres', NULL, NOW(), NOW()),
  (19,  'Rua',      'Primeiro de Janeiro', NULL, NOW(), NOW()),
  (20,  'Travessa', 'Primeiro de Janeiro', NULL, NOW(), NOW()),
  (21,  'Praça',    'João Carneiro', NULL, NOW(), NOW()),
  (22,  'Rua',      'Liberdade', NULL, NOW(), NOW()),
  (23,  'Rua',      'Manoel C. de Souza', NULL, NOW(), NOW()),
  (24,  'Rua',      'Manoel Novaes', NULL, NOW(), NOW()),
  (25,  'Travessa', 'Manoel Novaes', NULL, NOW(), NOW()),
  (26,  'Rua',      'Morro do Chapéu', NULL, NOW(), NOW()),
  (27,  'Travessa', 'Morro do Chapéu', NULL, NOW(), NOW()),
  (28,  'Rua',      'Nova', NULL, NOW(), NOW()),
  (29,  'Rua',      'Padre Alfredo', NULL, NOW(), NOW()),
  (30,  'Travessa', 'Padre Alfredo', NULL, NOW(), NOW()),
  (31,  'Praça',    'Sé', NULL, NOW(), NOW()),
  (32,  'Rua',      'Quintino Alves', NULL, NOW(), NOW()),
  (33,  'Travessa', 'Quintino Alves', NULL, NOW(), NOW()),
  (34,  'Praça',    'Rinaldo Magalhães', NULL, NOW(), NOW()),
  (35,  'Rodovia',  'Assent. Alagoinhas', NULL, NOW(), NOW()),
  (36,  'Rua',      'Saudade', NULL, NOW(), NOW()),
  (37,  'Travessa', 'Saudade', NULL, NOW(), NOW()),
  (38,  'Rua',      'Senhor do Bomfim', NULL, NOW(), NOW()),
  (39,  'Rua',      'São José', NULL, NOW(), NOW()),
  (40,  'Rua',      'Sete de Setembro', NULL, NOW(), NOW()),
  (41,  'Rua',      'Santo Antonio', NULL, NOW(), NOW()),
  (42,  'Rua',      'Usina', NULL, NOW(), NOW()),
  (43,  'Rua',      'Direita', NULL, NOW(), NOW()),
  (44,  'Travessa', 'Florisvaldo M. de Freitas', NULL, NOW(), NOW()),
  (45,  'Rua',      'Flavio Mesquita', NULL, NOW(), NOW()),
  (46,  'Fazenda',  'Cajueiro', NULL, NOW(), NOW()),
  (47,  'Fazenda',  'Gonçalves', NULL, NOW(), NOW()),
  (48,  'Fazenda',  'Poços', NULL, NOW(), NOW()),
  (49,  'Fazenda',  'Bela Vista', NULL, NOW(), NOW()),
  (51,  'Fazenda',  'Eliege e Geraldo', NULL, NOW(), NOW()),
  (52,  'Fazenda',  'Água Nova', NULL, NOW(), NOW()),
  (53,  'Fazenda',  'Lages do Contorno', NULL, NOW(), NOW()),
  (54,  'Fazenda',  'Caratiu', NULL, NOW(), NOW()),
  (55,  'Fazenda',  '2 Irmãos', NULL, NOW(), NOW()),
  (56,  'Fazenda',  'Halane', NULL, NOW(), NOW()),
  (57,  'Fazenda',  'Umbaumba -Tombador', NULL, NOW(), NOW()),
  (58,  'Fazenda',  'Bom sossego', NULL, NOW(), NOW()),
  (59,  'Fazenda',  'Saco', NULL, NOW(), NOW()),
  (60,  'Rua',      'Humildes Jacobina-BA', NULL, NOW(), NOW()),
  (62,  'Rua',      'Conj. Hab. Jacobina3', NULL, NOW(), NOW()),
  (63,  'Rua',      'Lot. Pedro H. Ferreira', NULL, NOW(), NOW()),
  (64,  'Fazenda',  'Edvaldo Nunes', NULL, NOW(), NOW()),
  (67,  'Rua',      'Roberto Maia', NULL, NOW(), NOW()),
  (68,  'Fazenda',  'Brauna', NULL, NOW(), NOW()),
  (69,  'Fazenda',  'Sitio J Padre Cícero', NULL, NOW(), NOW()),
  (70,  'Rodovia',  'Tombador/Lages do Batata', NULL, NOW(), NOW()),
  (71,  'Avenida',  'Givaldo Avelino da Mota Av 4 Bairro Pedro Henrique Ferreira', NULL, NOW(), NOW()),
  (72,  'Rua',      'Ana Pinto Barbosa Rua 12 Bairro Pedro Henrique Ferreira', NULL, NOW(), NOW()),
  (73,  'Rua',      'Antonio Batista de Carvalho Rua 13 Bairro Pedro Henrique Ferreira', '(Mao Aberta)', NOW(), NOW()),
  (74,  'Avenida',  'Dilson Barbosa Av Nº 6 Bairro Pedro Henriqe Ferreira', NULL, NOW(), NOW()),
  (75,  'Rua',      'Francisco Fidélix da Silva, Rua 22 Bairro Pedro Henrique Ferreira', 'Chico Mariano', NOW(), NOW()),
  (76,  'Rua',      'Francisco Matos Rua 7 do Bairro Pedro Henrique Ferreira', '(Chico do Bode)', NOW(), NOW()),
  (77,  'Rua',      'Hostilo  Quintino Alves Rua Nº 16 Bairro Pedro Henrique Ferreira', NULL, NOW(), NOW()),
  (78,  'Rua',      'José Carneiro da Silva, Rua 10 Bairro Pedro Henrique Ferreira', NULL, NOW(), NOW()),
  (80,  'Rua',      'José Moura de Souza Rua 19 do Bairro Pedro Henrique Ferreira', '(Zeca Pedro)', NOW(), NOW()),
  (82,  'Rua',      'José Severino Neto Rua 15 Bairro Pedro Henrique Ferreira', '(Zé Macedo)', NOW(), NOW()),
  (83,  'Rua',      'Manoel Nogueira da Silva Rua 23 Bairro Pedro Henrique Ferreira', NULL, NOW(), NOW()),
  (84,  'Avenida',  'Mário Alves de Amorim, Av Nº 5  Bairro Pedro Henrique Ferreira', '(Sr. Zulego', NOW(), NOW()),
  (85,  'Rua',      'São Francisco Rua 21 Bairro Pedro Henrique Ferreira', NULL, NOW(), NOW()),
  (86,  'Avenida',  'Genézio José de Miranda Av 3 Bairro Loteamento Pedro Henrique', '(Sr. Dinho)', NOW(), NOW()),
  (87,  'Rua',      'Medeiros- Bairro Vila Pamponet', 'Primeira Rua do Vila Bairro Pamponet', NOW(), NOW()),
  (88,  'Rua',      'Cravo- Bairro Vila Pamponet', 'Segunda Rua do Bairro Vila Pamponet.', NOW(), NOW()),
  (89,  'Rua',      'dos Evangelicos - Bairro Vila Pamponet', 'Terceira Rua do Bairro Vila Pamponet', NOW(), NOW()),
  (90,  'Rua',      'Otaciana Benícia de Jesus Rua Nº 20 Bairro Pedro Henrique Ferreira', 'Dona Baia', NOW(), NOW()),
  (91,  'Avenida',  'Raul Mangabeira  Av 2 Bairro Pedro Henrique Ferreira', NULL, NOW(), NOW()),
  (92,  'Rua',      'Maria Brito de Souza Rua 18 Bairro Loteamento Pedro Henrique', '(Dona Zainha)', NOW(), NOW()),
  (93,  'Rua',      'Terezinha Soares da Silva Rua 16 Bairro Pedro Henrique Ferreira', '(Tereza)', NOW(), NOW()),
  (94,  'Rua',      'José  Correia da Silva Rua 11 Bairro Loteamento Pedro Henrique Ferreira', NULL, NOW(), NOW()),
  (95,  'Rua',      'José Ferreira Filho Rua 17 Bairro Pedro Henrique Ferreira', NULL, NOW(), NOW()),
  (96,  'Fazenda',  'Água Nova -Sitio Terra Prometida - zona rural', NULL, NOW(), NOW()),
  (97,  'Fazenda',  'Água Nova -Sítio Morada dos Pássaros - zona rural', NULL, NOW(), NOW()),
  (98,  'Fazenda',  'São José', NULL, NOW(), NOW()),
  (99,  'Fazenda',  'Riacho das Flores', NULL, NOW(), NOW()),
  (100, 'Fazenda',  'Santo Antônio', 'Cadastro de atualização da antiga fazenda Cajueiro de Maria Neusa', NOW(), NOW()),
  (101, 'Travessa', 'Flavio Mesquita - Vila Margarida', NULL, NOW(), NOW());
